name: Black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .vevn/bin/activate
        python -m pip install --upgrade pip
        pip install black

    - name: Check code format with black
      run: |
        source .vevn/bin/activate
        black --check .
